language: node_js
node_js:
  - node

os:
  - osx

env:
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder ELECTRON_CACHE=$HOME/.cache/electron

matrix:
  include:
    - stage: release
      script: yarn release

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

before_install:
  - brew install rpm

cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
    - flow-typed
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn lint
  - yarn flow
  # HACK: Temporarily ignore `yarn test` on linux
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn test; fi
  # - yarn build-e2e
  # - yarn test-e2e

