language: node_js
node_js:
  - node

os:
  - osx

env:
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder ELECTRON_CACHE=$HOME/.cache/electron

matrix:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn flow
        - yarn test
        # TODO: Build E2E tests
        # - yarn build-e2e
        # - yarn test-e2e

    - stage: release
      script:
        - brew install rpm
        - yarn release


before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
  - brew cleanup

cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
    - flow-typed
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/Library/Caches/Homebrew

